services:
  foodexpress:
    build: .
    container_name: foodexpress_api
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    
  frontend:
    build: ./frontend
    container_name: foodexpress_frontend
    restart: unless-stopped
    ports:
      - "5173:80" # maps container's Nginx 80 port to host 5173
    depends_on:
      - foodexpress

  mongo:
    image: mongo:7
    container_name: foodexpress_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: foodexpress
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
